name: Build and publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build_app:
    name: Build and publish app
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo source code from GitHub.
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies.
      - name: Install dependencies
        run: npm install

      # Builds the app.
      - name: Build the app
        run: npm run build

      # Publish to NPM
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
